const assert = require('node:assert/strict');
const fs = require('node:fs');
const { JSDOM } = require('jsdom');
const dom = new JSDOM('<section class="trip-summary"><button id="btnEmpezarViaje">Empezar viaje</button><ol class="trip-steps"><li><strong>🚶 Caminá</strong></li><li data-bajada-nombre="Tres Cruces" data-bajada-lat="-34.9" data-bajada-lon="-56.2"><strong>🚌 Tomá el 494</strong></li><li><strong>🚶 Llegá</strong></li></ol></section><div id="mapa"></div>', {url:'https://example.test/',runScripts:'outside-only',pretendToBeVisual:true});
const w = dom.window, d = w.document;
let watches = 0, clears = 0, notices = [], closed = 0, message;
Object.defineProperty(w.navigator,'geolocation',{value:{watchPosition:()=>++watches,clearWatch:()=>clears++}});
w.Notification = {permission:'granted',requestPermission:async()=>{throw Error('No pedir permiso ya concedido');}};
const registration = {scope:'https://example.test/',showNotification:async(title,options)=>notices.push({title,options}),getNotifications:async()=>[{close:()=>closed++}]};
Object.defineProperty(w.navigator,'serviceWorker',{value:{getRegistration:async()=>registration,addEventListener:(_,fn)=>message=fn}});
w.HTMLElement.prototype.scrollIntoView = ()=>{};
w.eval(fs.readFileSync('guia-viaje.js','utf8'));
w.eval(fs.readFileSync('seguimiento-viaje.js','utf8'));
const click=id=>d.getElementById(id).click();
const tick=()=>new Promise(r=>setTimeout(r,0));
(async()=>{
  click('btnEmpezarViaje'); await tick();
  assert.equal(notices.length,1);
  assert.equal(notices[0].options.tag,'donde-viene-viaje-activo');
  assert.equal(notices[0].options.data.tipo,'viaje-activo');
  click('btnSeguirViaje');
  assert.equal(watches,1);
  const paso=d.getElementById('progresoGuiaViaje').textContent;
  click('btnSalirGuiaViaje');
  assert.equal(clears,0,'minimizar mantiene el mismo watch GPS');
  assert(d.body.classList.contains('trip-tracking-active'));
  assert.equal(d.getElementById('btnEmpezarViaje').textContent,'Viaje en curso');
  assert(!d.getElementById('btnVolverGuiaViaje').hidden);
  click('btnVolverGuiaViaje');
  assert.equal(d.getElementById('progresoGuiaViaje').textContent,paso);
  assert.equal(watches,1);
  assert.equal(notices.length,1,'reabrir no duplica notificaciones');
  click('btnSalirGuiaViaje');
  message({data:{tipo:'abrir-viaje-activo'}});
  assert(!d.getElementById('guiaViaje').hidden);
  click('btnTerminarGuiaViaje'); await tick();
  assert.equal(clears,1);
  assert.equal(closed,1);
  assert(d.getElementById('btnVolverGuiaViaje').hidden);
  assert(!d.body.classList.contains('trip-tracking-active'));
  w.Notification.permission='default';
  click('btnEmpezarViaje'); await tick();
  assert.equal(notices.length,1,'sin permiso no envía ni pide automáticamente');
  w.Notification.requestPermission=async()=>{w.Notification.permission='granted';return 'granted';};
  click('btnAvisoViaje'); await tick();
  assert.equal(notices.length,2);
  w.dispatchEvent(new w.Event('donde-viene:viaje-cambio')); await tick();
  assert(d.getElementById('guiaViaje').hidden);
  assert.equal(closed,2);
  dom.window.close();
  console.log('Viaje activo: minimizar conserva GPS/paso/paradas, reabrir, aviso con permiso, finalizar y cambio de ruta OK');
})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1;});
